task: "backTest" #"backTest"|"realtimeTrade"
taskID: "2024-05-31-19127374895"
dataOrigin:
  timeFrame:
    seconds: 1 #string, seconds 초 단위, example: "300s"
  productID: "stock.aapl.us" #{type}.{symbol}.{locale}
  productType: "stock" #"option"|"stock"|"crypto"
  startTimestamp: 12345678 #long(int64),Unix timestamp(epoch time), realtime일 때는 미적용.
  endTimestamp: 12345678 #long(int64),Unix timestamp(epoch time), realtime일 때는 미적용.
model: #model field가 없으면 외부 모델을 사용하지 않는 유즈케이스이다.
  ID: "goooo" #string
  batchSize: 100 #int
  outputType: "candlestick" #"candlestick"|"valueList"|"probeDist"
  params: #map[string]float32
    param1: 3.14
strategy:
  ID: "boolean" #string
  inputType: "candlestick" #"candlestick"|"valueList"|"probeDist"
  params: #map[string]float32
    param1: 3.14
