pipeline:
  fetchJob:
    isRealTime: true //boolean
    productType: "stock" // "stock"|"crypto"...etc
    startTime: 1234523445 // int64 시작 시각 타임스탬프. 
    timeSilce: "5m"
    additionalParmas:
      -key1: "value1"
  modelExecJob:
    name: "model__fractal-stock-probeDist" #단순 예시, uuid가 올 수도 있음
    additionalParmas:
  adaptJob:
    name: "adapt__probeDist-to-probeDist"
    additionalParmas:
  analyzerJob:
    name: "analyze__Kelly-bet"
    initialAsset: 100
    additionalParmas:
      - tendencyIndex: 3.0 #투자 성향. 높을수록 공격형. 안정형이면 캘리기준보다 작게 배팅, 높으면 더 크게 배팅
  
