// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package executer

import (
	"github.com/Goboolean/common/pkg/resolver"
	"github.com/Goboolean/core-system.worker/internal/infrastructure"
	"github.com/Goboolean/core-system.worker/internal/job"
)

// Injectors from wrie_setup.go:

func initalizeMock(p *job.UserParams) (ModelExecutor, error) {
	executerKServeConfig := provideKServeConfig()
	kServeClientImpl, err := provideKServe(executerKServeConfig)
	if err != nil {
		return nil, err
	}
	mock, err := NewMock(kServeClientImpl, p)
	if err != nil {
		return nil, err
	}
	return mock, nil
}

// wrie_setup.go:

type kServeConfig resolver.ConfigMap

func provideKServeConfig() kServeConfig {
	return kServeConfig(resolver.ConfigMap{})
}

func provideKServe(c kServeConfig) (*infrastructure.KServeClientImpl, error) {
	in := resolver.ConfigMap(c)
	return infrastructure.NewKServeClient(&in)
}
