// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: api/worker-handler.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WorkerHandler_WaitForTask_FullMethodName = "/api.WorkerHandler/WaitForTask"
)

// WorkerHandlerClient is the client API for WorkerHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerHandlerClient interface {
	WaitForTask(ctx context.Context, in *WorkerStatus, opts ...grpc.CallOption) (*TaskStatus, error)
}

type workerHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerHandlerClient(cc grpc.ClientConnInterface) WorkerHandlerClient {
	return &workerHandlerClient{cc}
}

func (c *workerHandlerClient) WaitForTask(ctx context.Context, in *WorkerStatus, opts ...grpc.CallOption) (*TaskStatus, error) {
	out := new(TaskStatus)
	err := c.cc.Invoke(ctx, WorkerHandler_WaitForTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerHandlerServer is the server API for WorkerHandler service.
// All implementations must embed UnimplementedWorkerHandlerServer
// for forward compatibility
type WorkerHandlerServer interface {
	WaitForTask(context.Context, *WorkerStatus) (*TaskStatus, error)
	mustEmbedUnimplementedWorkerHandlerServer()
}

// UnimplementedWorkerHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedWorkerHandlerServer struct {
}

func (UnimplementedWorkerHandlerServer) WaitForTask(context.Context, *WorkerStatus) (*TaskStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitForTask not implemented")
}
func (UnimplementedWorkerHandlerServer) mustEmbedUnimplementedWorkerHandlerServer() {}

// UnsafeWorkerHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerHandlerServer will
// result in compilation errors.
type UnsafeWorkerHandlerServer interface {
	mustEmbedUnimplementedWorkerHandlerServer()
}

func RegisterWorkerHandlerServer(s grpc.ServiceRegistrar, srv WorkerHandlerServer) {
	s.RegisterService(&WorkerHandler_ServiceDesc, srv)
}

func _WorkerHandler_WaitForTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerHandlerServer).WaitForTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerHandler_WaitForTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerHandlerServer).WaitForTask(ctx, req.(*WorkerStatus))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerHandler_ServiceDesc is the grpc.ServiceDesc for WorkerHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.WorkerHandler",
	HandlerType: (*WorkerHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WaitForTask",
			Handler:    _WorkerHandler_WaitForTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/worker-handler.proto",
}
