name: 'Auto Assign'

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add_assignees:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'payhere-ci[bot]' }}
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}