name: CI

env:
  INFLUXDB_URL: http://localhost:8086
  INFLUXDB_BUCKET: bucket
  INFLUXDB_TOKEN: token
  INFLUXDB_ORG: org
  INFLUXDB_TRADE_BUCKET: trade
  INFLUXDB_ORDER_EVENT_BUCKET: orderEvent
  INFLUXDB_ANNOTATION_BUCKET: annotation
  
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.2"
          
      - name: Run Tests
        run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.22.0"
     
      - name: Run Lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: latest
