name: Deploy

env:
  HOST:     ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  KEY:      ${{ secrets.SSH_KEY }}
  PORT:     ${{ secrets.PORT }}
  DIR:      ${{ secrets.DIR }}

on:
  workflow_run:
    workflows: [test]
    branches: feature/cicd
    types:
      - completed

jobs:
  Deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: ${{ env.PORT }}
          source: "."
          target: ${{ env.DIR }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: ${{ env.PORT }}
          script: |
            cd ${{ env.DIR }}
            make build-app
