name: test

env:
  HOST:     ${{ secrets.TEST_HOST }}
  USERNAME: ${{ secrets.TEST_USERNAME }}
  KEY:      ${{ secrets.TEST_SSH_KEY }}
  PORT:     ${{ secrets.TEST_PORT }}
  DIR:      ${{ secrets.TEST_DIR }}

on:
  push:
    branches:
      - feature/cicd

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: ${{ env.PORT }}
          source: "."
          target: ${{ env.DIR }}

      - name: Test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: ${{ env.PORT }}
          script: |
            cd ${{ env.DIR }}
            make test-app

