name: Auto Assign

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  add_assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
