name: Verify Test Code

on:
  pull_request:
    branches:
      - develop
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEVELOP_HOST }}
          username: ${{ secrets.DEVELOP_USERNAME }}
          key: ${{ secrets.DEVELOP_SSH_KEY }}
          port: ${{ secrets.DEVELOP_PORT }}
          source: "."
          target: ${{ secrets.TEST_DIR }}

      - name: Test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEVELOP_HOST }}
          username: ${{ secrets.DEVELOP_USERNAME }}
          key: ${{ secrets.DEVELOP_SSH_KEY }}
          port: ${{ secrets.DEVELOP_PORT }}
          script: |
            cd ${{ secrets.TEST_DIR }}
            make test-app
